### ISSUE TITLE
Improvement/cscli explain : allow options to provide crowdsec path and config path

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1041]

**Comment by mmetc** [comment]
This is more tricky than it seems at first.

Changing location for all the configuration files, db etc. to new OSs or test environments can be hard and prone to errors. For example:

- Defaults for `/etc/crowdsec` (and some of its subpaths) are hardcoded in sources, and cannot be changed at build time (in many distros, the default itself should be `/usr/local/etc/crowdsec`). I tried to do the changes in Go to specify `/etc/crowdsec` via -X and it became unfunny pretty soon. Same goes for `/var/lib` which is `/var/db` in FreeBSD. The current method is to replace paths by running `/bin/sed` over a (manually built) list of .go and .yaml files before compiling. 

- The main configuration file is, by default, stored in a directory that is specified by the configuration file itself. While this can make sense, it is not intuitive.

- Each sub-configuration file must be referenced by the its absolute path, otherwise it is unclear what the base directory is (maybe: the CWD at the time the server was run?) or even what it should be (_config_dir_ for most, but _hub_dir_ for _index_path_ and _data_dir_ for _db_path_). In the current situation, relative paths should be forbidden or deprecated. I even wonder if getting rid of _config_dir_, _hub_dir_ and _data_dir_ is not a better idea.

- Configuration backup via cscli cannot work with a non-standard setup (ex. _acquisition_path_ outside _config_dir_).

**Comment by LaurenceJJones** [comment]
@buixor This still an issue cscli has option for config path. Dont know about the `crowdsec path`??

**Comment by mmetc** [comment]
The crowdsec binary is searched in $PATH,  while for example in the hub tests, its location can be provided as parameter. The config path is meant to be the configuration of crowdsec, not cscli.

**Comment by mmetc** [comment]
The option for path to crowdsec binary has been added in https://github.com/crowdsecurity/crowdsec/pull/1983

We still use the same --config option for both cscli and the invoked crowdsec. Do we need a --crowdsec-config too?

**Comment by buixor** [comment]
I don't think we need `--crowdsec-config` let's see if it is needed in the future
