### ISSUE TITLE
Improvement/ metabase work with config_db=postgresql / mysql

### ISSUE THREAD

**Issue by parisni** [crowdsecurity/crowdsec#1071]
AFAIK, metabase deployment only works with sqlite:

> cscli dashboard setup
> For metabase docker to be able to access SQLite file we need to add a new group called 'crowdsec' to the system, is it ok for you ? 

But crowdsec proposes sqlite, mysql and postgresql as backend. Is there a way to make metabase handle them ?

**Comment by LaurenceJJones** [comment]
Closing as not planned due to the fact of `enterprise` plan is needed to support these.

**Comment by Zegorax** [comment]
Hello,

I think what @parisni meant is to speak to the Crowdsec database via MySQL/PostgreSQL instead of the local sqlite database.

The only thing needed would be a translation of the SQLITE requests in the metabase dashboards to either DB language.

I've tried myself, it's mostly working and require a little bit of tuning.

**Comment by morph027** [comment]
Little hack:

Installed [Sequel: The Database Toolkit for Ruby](https://github.com/jeremyevans/sequel) and created a sqlite dump from the postgres database.

```
mkdir -p /metabase-data
sequel -C postgres://<user>:<password>@<host>/<dbname> sqlite:///metabase-data/crowdsec.db
```
