### ISSUE TITLE
Bug/FalsePositive when logging into Mattermost

### ISSUE THREAD

**Issue by zell-mbc** [crowdsecurity/crowdsec#1464]
Mattermost clients which logon to their backend service get banned

**Describe the bug**
For the last couple of weeks I have been getting Mattermost user complaints about not being able to logon. Highly erratic behaviour where login wasn't possible with service not found messages and a few hours later things would work again.
Well, to cut a somewhat long troubleshooting story short, it turned out to be Crowdsec which since some point recently views Mattermost clients looking for backend services as attackers and blocks the IP for 4 hours.
From the crowdsec log I can see that users get banned for two reasons, crowdsecurity/http-probing and http-crawl-non_statics as shown in the example below.

I have read up somewhat on creating a Whitelist, but whitelisting IPs is not practicle given that I don't know how users will connect, and I don't know how I can whitelist a service?
 
```
sudo cscli decisions list
+----------+----------+-------------------+--------------------------------------+--------+---------+----------
|    ID    |  SOURCE  |    SCOPE:VALUE    |                REASON                | ACTION
| 11870524 | crowdsec | Ip:149.172.x.y    | crowdsecurity/http-crawl-non_statics | ban
```

**To Reproduce**
1. ssh into server running Mattermost & Crowdsec
2.  Run 'sudo cscli decisions list' to confirm the list is empty
3. Login from any Mattermost (PC/iOS/ANdroid) client
4. Run 'sudo cscli decisions list' again to find the IP is now blocked

**Expected behavior**
No ban

**Screenshots**
![image](https://user-images.githubusercontent.com/29018767/164225613-5a200dda-1aa6-48b5-ba86-ab2cc879d547.png)

**Technical Information (please complete the following information):**
 - OS: S: Ubuntu 20.04.4 LTS x86_64]

```
sudo cscli version                  
2022/04/20 14:05:46 version: v1.3.2-debian-pragmatic-b66366c28c9b0c8843913afb05c553e658513d63
2022/04/20 14:05:46 Codename: alphaga
2022/04/20 14:05:46 BuildDate: 2022-03-04_12:05:00
2022/04/20 14:05:46 GoVersion: 1.17.5
2022/04/20 14:05:46 Platform: linux
2022/04/20 14:05:46 Constraint_parser: >= 1.0, <= 2.0
2022/04/20 14:05:46 Constraint_scenario: >= 1.0, < 3.0
2022/04/20 14:05:46 Constraint_api: v1
2022/04/20 14:05:46 Constraint_acquis: >= 1.0, < 2.0

```

```
sudo cscli parsers list
PARSERS
------------------------------------------------------------------------------------------------------------------------------
 NAME                            📦 STATUS                    VERSION  LOCAL PATH                                             
------------------------------------------------------------------------------------------------------------------------------
 crowdsecurity/http-logs         ⚠️  enabled,update-available  0.7      /etc/crowdsec/parsers/s02-enrich/http-logs.yaml        
 crowdsecurity/apache2-logs      ✔️  enabled                   0.9      /etc/crowdsec/parsers/s01-parse/apache2-logs.yaml      
 crowdsecurity/dateparse-enrich  ✔️  enabled                   0.2      /etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml 
 crowdsecurity/syslog-logs       ⚠️  enabled,update-available  0.7      /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml         
 crowdsecurity/sshd-logs         ⚠️  enabled,update-available  1.6      /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml         
 crowdsecurity/nginx-logs        ⚠️  enabled,update-available  0.9      /etc/crowdsec/parsers/s01-parse/nginx-logs.yaml        
 crowdsecurity/whitelists        ✔️  enabled                   0.2      /etc/crowdsec/parsers/s02-enrich/whitelists.yaml       
 crowdsecurity/geoip-enrich      ✔️  enabled                   0.2      /etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml     
------------------------------------------------------------------------------------------------------------------------------

```

```
sudo cscli bouncers list
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 NAME                        IP ADDRESS  VALID  LAST API PULL              TYPE                       VERSION                                                           
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 FirewallBouncer-1638903463  127.0.0.1   ✔️      2022-01-27T13:41:05Z       crowdsec-firewall-bouncer  v0.0.22-debian-pragmatic-f64e94b59a948717c3dc848f9abebb27b5974714 
 nginx-1638903496            127.0.0.1   ✔️      2022-04-20T12:01:27Z       crowdsec-nginx-bouncer     v1.0.4                                                            
 FirewallBouncer-1641288331              ✔️      2022-01-04T10:25:31+01:00                                                                                               
 FirewallBouncer-1641288411              ✔️      2022-01-04T10:26:52+01:00                                                                                               
 FirewallBouncer-1643282766              ✔️      2022-01-27T11:26:06Z                                                                                                    
 FirewallBouncer-1643284753              ✔️      2022-01-27T11:59:13Z                                                                                                    
 FirewallBouncer-1648192919              ✔️      2022-03-25T07:21:59Z                                                                                                    
 nginx-1648193014                        ✔️      2022-03-25T07:23:34Z                                                                                                    
 nginx-1649420178                        ✔️      2022-04-08T12:16:18Z                                                                                                    
 nginx-1650104781                        ✔️      2022-04-16T10:26:21Z                                                                                                    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.

**Comment by Punkado** [comment]
I can confirm that i am having the same problem. Most of the clients are getting banned by crowdsecurity/http-crawl-non_statics in matter of hours after Crowdsec is activated.

**Comment by buixor** [comment]
Hello,

Can you provide some sample logs (mattermost http logs) of people triggering this ? Depending on how trivial it is, there are several possibilities :
 - we whitelist some URLs or prefix so that it doesn't trigger `http-crawl-non_statics`
 - disable or put  `http-crawl-non_statics` in simulation mode

We have a PR aiming at improving the `distinct` behavior (https://github.com/crowdsecurity/crowdsec/pull/1478) that might help with false positives in `http-crawl-non_statics`, but it won't be shipped before next release (so in a month or so).

In the meanwhile, can you try to significantly increase the `cache_size` parameter of `http-crawl-non_statics` scenario to ie. 20 and see if it reduces the amounts of false positives ?

Please let me know and/or don't hesitate to drop by on discord to do a live debug !

**Comment by zell-mbc** [comment]
I changed the cache_size to 20 and logged off/on a few times. So far no ban. I'll keep CrowdSec running over the weekend and will have a close eye on things…

**Comment by Punkado** [comment]
Changing the cache_size to 20 didn't solve the problem here, takes more time to people get banned but still happens. Probably because there much more other servers in the same server that the same ip is accessing, so the bucket get full with the time, and the user get the ip banned.

Here is a sample of logs of the mattermost:

`{"level":"debug","ts":1633094560974.6354961003,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users","request_id":"i6x4barmdj8r5uccihh5ow","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":16330978660974.642987059,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users/g1x6y6oqu6jnd8nka35iqa/channels/cpukebqo4ib4xdp7qnr7xqushe/posts/unread","request_id":"nbkmgyyds533dmmgp4amnec9froy","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":163309789065974.6673789172,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/channels/cpu4kebqo4ib4xdp7qnr7xqushe/stats","request_id":"utz1xt4ngj8buker9u4ngn5zyw","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":163309790974.789,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/roles/names","request_id":"fk11k16hxbg1qjqbc1gwj9y","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633096540974.74028768387,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/roles/names","request_id":"dk5oc4tj1tj8tjnd93xbta","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633056590974.7481358685,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"fjajzcdrk3fqank3hy","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633090974.7812321989,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/ids","request_id":"4uesqzig6dgfgfgotq3rdwzuh","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633090974.79366346416,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users","request_id":"rsbx1c7twqpffggfdny73wueguy","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":163453090974.8148688706,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users","request_id":"4hy75ruabdfgszh7erd11xyw","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":163563090974.8239456913,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users","request_id":"e5peotuteu7bcnbvntwxmsrs5ze","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":16354643090974.861654549,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users","request_id":"d5ira7xzyw7dgvbnyjgcdpd3ee","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633456090974.863101,"caller":"mlog/sugar.go:17","msg":"OK: ","plugin_id":"jira","Status":"200","Host":"web.site.com","RequestURI":"/plugins/jira/api/v2/userinfo","Method":"GET","query":""}
{"level":"debug","ts":1633090974.885179802,"caller":"web/handlers.go:107"{"level":"debug","ts":16345498.0799584,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"GET","url":"/api/v4/users/stats","request_id":"x3r8wbb4fghf9e95w8e","host":"web.site.com","scheme":"https","status_code":"200"}
^C{"level":"debug","ts":1633090999.381478986,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"xcqsq6kyvbnnserc11pr","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":16330909879999.7318789869,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1633090999.8253024,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"jfzz4w8dsprmnbmg15ze","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":16330914877000.870569,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"st4fmb4rc6ff98ghfgfhiumw","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633098967001.1696696,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1633095461004.750024,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"tbugghpimmifghxcrucem1e","host":"web.site.com","scheme":"https","status_code":"200"}
{"level":"debug","ts":1633045691004.8807864,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_typing"}
{"level":"debug","ts":1633094561006.0048747,"caller":"web/handlers.go:107","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"4ghgr7jmy3ijhjgh53bc4f4yzzo","host":"web.site.com","scheme":"https","status_code"`

End here, the traefik log:

`xxx.xxx.xxx.xxx - - [04/May/2022:10:11:09 +0000] "POST /api/v4/users/ids?since=165162148601550 HTTP/2.0" 200 406 "-" "-" 696777 "mattermost@docker" "http://172.18.0.7:8000" 3ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:09 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 588 "-" "-" 696778 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:11 +0000] "POST /api/v4/posts HTTP/2.0" 201 534 "-" "-" 696783 "mattermost@docker" "http://172.18.0.7:8000" 101ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:11 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 83 "-" "-" 696784 "mattermost@docker" "http://172.18.0.7:8000" 17ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:16 +0000] "POST /api/v4/posts HTTP/2.0" 201 493 "-" "-" 696801 "mattermost@docker" "http://172.18.0.7:8000" 55ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:16 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 83 "-" "-" 696802 "mattermost@docker" "http://172.18.0.7:8000" 21ms
    xxx.xxx.xxx.xxx- - [04/May/2022:10:11:21 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 852 "-" "-" 696806 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx- - [04/May/2022:10:11:21 +0000] "GET /api/v4/plugins/webapp HTTP/2.0" 200 920 "-" "-" 696807 "mattermost@docker" "http://172.18.0.7:8000" 0ms
    xxx.xxx.xxx.xxx- - [04/May/2022:10:11:21 +0000] "GET /api/v4/users/me/teams/dsfsdfsdf43rrertf/channels/members HTTP/2.0" 200 1482 "-" "-" 696808 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx- - [04/May/2022:10:11:21 +0000] "GET /api/v4/users/me/teams/dsfsdfsdf43rrertf/channels?include_deleted=true HTTP/2.0" 304 0 "-" "-" 696811 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:21 +0000] "GET /api/v4/channels/6piombsao338c3d9ff7po54crcizo/posts?since=1651572023353&skipFetchThreads=false&collapsedThreads=false&collapsedThreadsExtended=false HTTP/2.0" 200 59 "-" "-" 696809 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:21 +0000] "POST /api/v4/users/ids?since=1651654481101 HTTP/2.0" 200 2 "-" "-" 696812 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:21 +0000] "GET /api/v4/users/me/teams/unread HTTP/2.0" 200 118 "-" "-" 696810 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:25 +0000] "POST /api/v4/posts HTTP/2.0" 201 544 "-" "-" 696821 "mattermost@docker" "http://172.18.0.7:8000" 122ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:26 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 83 "-" "-" 696822 "mattermost@docker" "http://172.18.0.7:8000" 90ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:26 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 835 "-" "-" 696825 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:28 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 800 "-" "-" 696826 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:30 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 573 "-" "-" 696829 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "GET /api/v4/plugins/webapp HTTP/2.0" 200 920 "-" "-" 696834 "mattermost@docker" "http://172.18.0.7:8000" 1ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "GET /api/v4/channels/cmy5bsidb9jbxfdijzcxuddgh4ssa/posts?since=1651658211826&skipFetchThreads=false&collapsedThreads=false&collapsedThreadsExtended=false HTTP/2.0" 200 59 "-" "-" 696836 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 892 "-" "-" 696833 "mattermost@docker" "http://172.18.0.7:8000" 3ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "POST /api/v4/users/ids?since=1651650675319 HTTP/2.0" 200 406 "-" "-" 696838 "mattermost@docker" "http://172.18.0.7:8000" 6ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "GET /api/v4/users/me/teams/unread HTTP/2.0" 200 119 "-" "-" 696837 "mattermost@docker" "http://172.18.0.7:8000" 8ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "GET /api/v4/users/me/teams/dsfsdfsdf43rrertf/channels?include_deleted=true HTTP/2.0" 200 17960 "-" "-" 696839 "mattermost@docker" "http://172.18.0.7:8000" 12ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "GET /api/v4/users/me/teams/dsfsdfsdf43rrertf/channels/members HTTP/2.0" 200 8456 "-" "-" 696835 "mattermost@docker" "http://172.18.0.7:8000" 13ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "POST /api/v4/posts HTTP/2.0" 201 497 "-" "-" 696840 "mattermost@docker" "http://172.18.0.7:8000" 85ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:32 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 83 "-" "-" 696842 "mattermost@docker" "http://172.18.0.7:8000" 37ms
    xxx.xxx.xxx.xxx- - [04/May/2022:10:11:33 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 41 "-" "-" 696843 "mattermost@docker" "http://172.18.0.7:8000" 1ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:34 +0000] "POST /api/v4/channels/members/me/view HTTP/2.0" 200 41 "-" "-" 696844 "mattermost@docker" "http://172.18.0.7:8000" 1ms
   xxx.xxx.xxx.xxx - - [04/May/2022:10:11:38 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 1243 "-" "-" 696845 "mattermost@docker" "http://172.18.0.7:8000" 2ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:39 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 1094 "-" "-" 696848 "mattermost@docker" "http://172.18.0.7:8000" 1ms
    xxx.xxx.xxx.xxx - - [04/May/2022:10:11:41 +0000] "POST /api/v4/users/status/ids HTTP/2.0" 200 1385 "-" "-" 696851 "mattermost@docker" "http://172.18.0.7:8000" 2ms
 `

**Comment by LaurenceJJones** [comment]
Closing due to stale, however, if you want to raise as an issue again please open it on the hub side https://github.com/crowdsecurity/hub
