### ISSUE TITLE
[Feature] Docker - Remove collections if not in COLLECTIONS

### ISSUE THREAD

**Issue by modem7** [crowdsecurity/crowdsec#1910]
### What would you like to be added?

/kind enhancement

When removing collections in Docker via the `COLLECTIONS` variable, it does not remove the collections from Crowdsec itself. 

### Why is this needed?

When users remove collections they previously added, they may erroneously think that by removing their values in their Docker settings, it would remove it from the application itself.

**Comment by modem7** [comment]
The same should really apply to `SCENARIOS `and `PARSERS`

**Comment by LaurenceJJones** [comment]
/kind enhancement

Hmmm i understand the logic, however, with how collections are handled at the moment there a risk off accidental taints  #1118 . Plus we also install default collections: `crowdsecurity/linux crowdsecurity/docker` because crowdsec cant function without these so we would have to hardcode these in.
