### ISSUE TITLE
Bug/wizard doesn't properly detect apache2 on CentOS 7

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#195]
**Describe the bug**

Wizard doesn't detect apache2 on centos 7. Probably because the service is called httpd and the logs are in `/var/log/httpd/*.log`

**To Reproduce**
1. Run wizard on centos with apache2

**Expected behavior**
detect apache2 logs

**Technical Information (please complete the following information):**
 - OS: centos 7
 - Version: v0.3.0

**Comment by sbs2001** [comment]
This is repase from gitter chat 

As a start I decided to work on crowdsecurity/crowdsec#195 .
@buixor you mentioned the cause of problem to be either the service is called httpd and the logs are in /var/log/httpd/*.log . I did some research and found that the /var/log/httpd/*.log part is not the issue because the log locations for apache2 have it already defined at https://github.com/crowdsecurity/crowdsec/blob/cbbe210736736fb15ea03b8f7dbe24477485b9e7/wizard.sh#L134 .

The cause of issue is rather that the service is named httpd as you suggested .

For eg
On ubuntu , where the wizard runs as expected

```
shivam@shivam-UX430UAR:~/coding$ systemctl | grep "Apache"
  apache2.service         loaded active running   The Apache HTTP Server
```

While on my centos 7 VM I get :

```
[root@localhost httpd]# systemctl | grep "Apache"
httpd.service                 loaded active running   The Apache HTTP Server
```

the regex for httpd log path is an issue too `/var/log/*httpd*.log` wont match anything inside `/var/log/httpd/` . 

Essentially we need to fix :

1. Service discovery of `httpd`
2. Log discovery regex of `httpd`

**Comment by sbs2001** [comment]
On non RH distros (eg ubuntu) apache2 stores logs like `/var/log/apache2/access.log` while the same are stored as `/var/log/apache2/access_log` in RH distro (Centos 7 in this case) . 

@buixor  should the httpd be treated like separate service or should changes be made in handling of apache2 service ?
