### ISSUE TITLE
unix socket support

### ISSUE THREAD

**Issue by cyberb** [crowdsecurity/crowdsec#2197]
### What would you like to be added?

I would like to be able to not use any tcp ports and use only unix sockets.

### Why is this needed?

I am working on https://github.com/syncloud/platform project where I am allowing non tech users to run various popular services like crowdsec on a single (some times not very powerful) device. Apps are coming from the store and having ports does not really help. Many apps support unix socket, to some I have added it myself (https://github.com/matrix-org/dendrite/commit/985298cfc46cb6b33ab44d32a63a933d03e16429).
Are you open for such a feature, I could try to implement server side and probably in some bouncers.

/kind feature

**Comment by LaurenceJJones** [comment]
We have spoken about this internally for a while. However, finding a time to do it as well as going through the bouncer (underlying SDK https://github.com/crowdsecurity/go-cs-bouncer ) to support it takes some time to which we wouldn't know if people would use it.

I'm all for this feature and so are the team as it would help solo users since they wouldn't need to bind a port if they are not exposing the API.

**Comment by mmetc** [comment]
Thanks @LaurenceJJones , just a note

> this is where the connection code should live.

Yes if the code is reusable for both crowdsec and bouncers. If it's only for bouncers it can stay in go-cs-bouncer. Let me know if you need help for the functional tests

**Comment by LaurenceJJones** [comment]
Closing issue due to feature being released as of `1.6.1`, however, currently none of the remediation components support unix sockets.

Firstly we will distribute support via our [golang lib](https://github.com/crowdsecurity/go-cs-bouncer) which will be tracked as [this issue](https://github.com/crowdsecurity/go-cs-bouncer/issues/44).

Closing issue as completed in main CrowdSec codebase.
