### ISSUE TITLE
missing tag on docker hub "v1.6.1"

### ISSUE THREAD

**Issue by xsolinsx** [crowdsecurity/crowdsec#2974]
### What happened?

I noticed that crowdsec GUI was suggesting me to update my container instance from v1.6.0 to v1.6.1
But I configured a service to notify me when a container has a new image version according to the tag (WhatsUpDocker)
So I checked and I noticed that the tag "v1.6.1" is not present on docker hub, only "v1.6.1-something", and that's why I was not notified for the update

### What did you expect to happen?

The tag "v1.6.1" should be present in docker hub as was "v1.6.0" and it should point to the latest v1.6.1 build (v1.6.1-2 at the time of writing)

### How can we reproduce it (as minimally and precisely as possible)?

No reproduction needed, it's just missing from the docker hub and needs to be added

### Anything else we need to know?

Sorry if it's not a proper bug but I thought this was the most appropriate issue type

### Crowdsec version

v1.6.0

### OS version

NA

### Enabled collections and parsers

NA

### Acquisition config

NA

### Config show

NA

### Prometheus metrics

NA

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

NA

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

We changed this now as of `1.6.2` to be correct, however, since we now decoupled docker deployments away from the main version of crowdsec there may be image variants such as `1.6.1-1` which is a patch to the docker deployment.

We aim to stay away from using this as much as possible, however, from `1.6.0` to `1.6.1` we had many issues with changes to docker which have now stabilized
