### ISSUE TITLE
Bouncer lastPull strategy change (Allow bouncer to use stream mode while sharing same API key)

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#3255]
### What would you like to be added?

Currently, bouncer sharing the same API key cannot reliably use the stream mode.

**What happens**

When a bouncer queries `/decisions/stream` with `startup` not set to true, we rely on `bouncerInfo.LastPull` timestamp to know when the bouncer last pulled and know which data should be returned. the `bouncerInfo` is fetched from the DB and only relies on the API key provided by the bouncer.

**Problem**

However, this is problematic when several bouncer instances (ie. nginx-ingress / kube) share the same API key and want to use stream mode: they get inconsistent data as they all share the same entry in the DB and thus `LastPull`.

**Proposed change**

The proposed change is the following:
 - Use combo IP + Api Key as the unique identified for bouncers (instead of just API key)
 - When a "new" bouncer (existing api key but new IP) comes in, after authentication, we duplicate the existing row (based on api key) and we update last pull, heartbeat etc.
 - When a bouncer does a queries `/decisions/stream` with `startup` not set to true, we rely on the Api key + IP combo to select the relevant row, so that each bouncer instance get its own `LastPull`

### Why is this needed?

Allow several bouncers to share the same API key and use stream mode.

**Comment by rohow** [comment]
HI~ Is there any related fix plan for this issue? I am currently using multi-agent mode in ingress-nginx and there will be problems when updating in stream mode.

I think it should be related to this. I haven't found a way to use helm deployment to allow each agent to have a different api key.

**Comment by LaurenceJJones** [comment]
> HI~ Is there any related fix plan for this issue? I am currently using multi-agent mode in ingress-nginx and there will be problems when updating in stream mode.
> 
> I think it should be related to this. I haven't found a way to use helm deployment to allow each agent to have a different api key.

Hey 👋🏻 Yes we have floated some ideas internally around how we can move forward on this issue and yes the reason behind the issue was when we helping enterprise clients on a k8s environments without moving them over to [mTLS authentication](https://docs.crowdsec.net/docs/next/local_api/tls_auth) it currently does not allow stream mode with the API key.

**Comment by hslatman** [comment]
Hey! Was lead here after https://github.com/hslatman/caddy-crowdsec-bouncer/issues/55 and https://github.com/crowdsecurity/go-cs-bouncer/issues/47. 

It's probably a good start to use IP + API Key, but there can be situations in which there are multiple bouncers operating from the same IP (from the viewpoint of CAPI). For these cases an alternative approach may be needed, for example by including some "soft" uniquely identifying a single bouncer. This could be a random name generated at bouncer startup, and then recorded on the CAPI side. The bouncer would have to send it with each poll. Instead of recording it as a separate machine, it could be viewed as an additional "subscription channel" from a single machine. This approach could be combined with tracking the IP.

**Comment by LaurenceJJones** [comment]
>  (from the viewpoint of CAPI)
CAPI doesnt use api keys, it uses a username / password within `online_api_credentials.yaml`, if its more about metrics sent to capi then yes, if you currently dont use an unique api key per remediation then it simply just one remediation and this issue/PR would show them as unique.

We are looking to implement this shortly as with orchestration software like k8s and if you use a remediation that _cannot_ use mTLS for example `nginx` then it very difficult to automate the api keys without having an external init container that uses `cscli` to interact with the database.

**Comment by hslatman** [comment]
> > (from the viewpoint of CAPI)
> 
> CAPI doesnt use api keys, it uses a username / password within `online_api_credentials.yaml`, if its more about metrics sent to capi then yes, if you currently dont use an unique api key per remediation then it simply just one remediation and this issue/PR would show them as unique.

@LaurenceJJones sorry, meant LAPI instead of CAPI.

> We are looking to implement this shortly as with orchestration software like k8s and if you use a remediation that _cannot_ use mTLS for example `nginx` then it very difficult to automate the api keys without having an external init container that uses `cscli` to interact with the database. Then obviously cleanup becomes a chore and we want to improve this process 😅

Absolutely makes sense to do so, yes. 

> We currently dont have a field for an alias naming scheme, this can be useful for a UX pov as you state there might be cases where you want to run an api key per node that has multiple remediation, however, with the current LAPI v1 we calculate the delta of difference based on api keys, plus soon the IP, if we add another naming to the mix it might break backwards compatibility, however, it obvious could be just null/nil for older ones.

Indeed, the new behavior with an alias/additional identifier should be opt-in, at least initially. I do think that it would be nice to support something like that (in addition to the IP), though, so that it can be fully controlled.
