### ISSUE TITLE
Improvement/config Local configuration files should not be stored in same location as crowdsec files

### ISSUE THREAD

**Issue by zathras777** [crowdsecurity/crowdsec#334]
Given that crowdsec installs installs it's own configuration files, when developing and tweaking these files locally they should be in a different location to keep upgrades simpler and trouble free. A lot of apps do this and it makes managing the app far simpler. The inclusion of "tainted" and "local" on the **_cscli list_** output is good, but doesn't resolve the issue with potential updates.

**Comment by buixor** [comment]
Thanks for the suggestion, it definitely makes sense :)
I don't know exactly how to achieve this yet, so I will let this issue open so we can elaborate (feel free if you have any suggestions).

Have you looked at the `cscli backup` command? It is used by `wizard --upgrade` and should as well allow to easily "snapshot" a complete crowdsec configuration, it might be a partial answer.

**Comment by zathras777** [comment]
By way of an example, I need to adjust the filter entry for the postfix-logs.yaml file on my configuration, but doing so results in the following

crowdsecurity/postfix-logs      ⚠️  enabled,tainted  ?        /etc/crowdsec/config/parsers/s01-parse/postfix-logs.yaml

When upgrading this will likely result in issues :-( It would be better if I could have a seperate, local postfix-logs.yaml file with just my revised filter line so that updates could run without issue and my local configuration wouldn't be affected. 

Additionally, the local file location could allow for development and experimentation without affecting the main centrally managed files.

**Comment by ririsoft** [comment]
Hello,

I would recommend that you follows the "Linux Standard Base" and have the Wizard install files into "/opt" or "/usr/local/lib" instead of "/etc".

You may also get inspiration from the excellent work done by systemd regarding configuration files, where files from /etc overrides files from the system installation. Even better, you can overwrite only a part of a configuration file.

If you consider the apache logs for instance: most people will want to only customize the pattern and let the rest of the configuration unchanged.

This drastically simplifies maintenance and makes upgrades safer.

To be honest I find he current experience with "tainted" configuration very confusing. First the "tainted" word suggest something is going wrong. It was confusing to me the first time I saw it. Then I am not able to *diff* my current tainted configuration with the one from the hub easily from the command line: this is particularly important on upgrades.

I hope it helped !

**Comment by buixor** [comment]
Hello there,

The following topic (related to this discussion) is opened here : https://discourse.crowdsec.net/t/request-for-comments-parsers-scenarios-customization-in-the-crowdsec-agent/129

**Comment by buixor** [comment]
There are some future evolution of the hub that are going to help deal with this (when it comes to parsers and scenarios).
When it comes to configuration itself, we merged https://github.com/crowdsecurity/crowdsec/pull/1497 that should solve this in 1.4
