### ISSUE TITLE
Watchman Report - State missing

### ISSUE THREAD

**Issue by Dzoker2** [crowdsecurity/crowdsec#3345]
### What happened?

In Home Assistant, Watchman keep reporting this 4 lines

| alert.signature_id             | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:62                   
| alert.rev                      | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:64                    |
| alert.signature                | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:66                    
| alert.severity                 | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:68   

### What did you expect to happen?

I guess not to see the reported

### How can we reproduce it (as minimally and precisely as possible)?

Run Watchman [https://github.com/dummylabs/thewatchman](url)

### Anything else we need to know?

No

### Crowdsec version

1.6.3

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

From what I can see watchman should not be monitoring these files as these files are not something to do with Home Assistant but our own software.

So I would suggest to use the ignore files options in watchman and add `.storage/crowdsec/config/*` if possible as these files cant be modified to have home assistant / watchman attributes since it will fail our schema validation.

**Comment by Dzoker2** [comment]
I did look to exclude .storage/crowdsec/config/* in watchman but the exclusion portion in watchman is asking for "comma-separated list of entities and actions" to be excluded from tracking, not the path
