### ISSUE TITLE
Improvement/logging

### ISSUE THREAD

**Issue by registergoofy** [crowdsecurity/crowdsec#502]
Please, start your issue name (after `improvement`) with the component name impacted by this feature request and a small description of the FR. Example: `Improvement/cscli: add this feature ....` and remove this line :)

**Is your feature request related to a problem? Please describe.**
crowdsec is gnerating a lot of logs. These logs are dispatched in a bunch of files.

**Describe the solution you'd like**
These should be droped in a directory /var/log/crowdsec

**Example of what you imagine**
`/var/log/crowdsec` populated with crowdsec logs and bouncer logs. We can also add a logrotate configuration.

**Comment by mercyground** [comment]
#Example /etc/logrotate.d/crowdsec file (works on ubuntu 20.04. Requires su due otherwise permissions error)
`/var/log/crowdsec.log {
  su root syslog
  rotate 12
  monthly
  compress
  missingok
  notifempty
  postrotate
      systemctl reload crowdsec
  endscript
}

/var/log/crowdsec_api.log {
  su root syslog
  rotate 12
  monthly
  compress
  missingok
  notifempty
  postrotate
      systemctl reload crowdsec
  endscript
}
`

**Comment by buixor** [comment]
I think this has overall greatly improved with log level control and separation of API / crowdsec logs. I would tend to consider this closed with 1.1.0
