### ISSUE TITLE
Improvement/lapi: add check to lapi to check client status

### ISSUE THREAD

**Issue by jamiew0w** [crowdsecurity/crowdsec#761]
**Is your feature request related to a problem? Please describe.**

It's hard to tell. Currently `cscli machines list` shows _all_ machines with a ✔️ Status even if they haven't reported to the server in ~2 weeks. 

I frequently build/destroy machines and would like to keep validated machines somewhat tidy so if there was a check added to lapi we could easily tell which are offline (and maybe for how long?).

**Describe the solution you'd like**

Something straightforward like:

`cscli machines check`

If it responds, status stays ✔️, if it doesn't it changes to X.

**Comment by buixor** [comment]
Hello @jamiew0w !

Thanks for the issue, and I agree that this should be improved.

There is currently no mechanism that allows the local api to ping the agents, but we'll try to suggest something to make it more friendly. Maybe we could simply change the status based on the time elapsed since the machine last connected / pushed information ?
