### ISSUE TITLE
Question: Is it bag or a feature? Duplicated decisions.

### ISSUE THREAD

**Issue by SanchosPancho** [crowdsecurity/crowdsec#827]
In my production environment I've some problems with CrowdSec. I've massive bruteforce attack from million proxies.

My filter:
capacity: 5
leakspeed: 60m
blackhole: 10s

My bouncer:
crowdsec custom bouncer - which execute bash script. Bash script go to some external api service and ban ip.

Problem:
Due massive bruteforce attack, before custom bouncer ban attacker ip, this ip can make 100+ requests to my app, in this way, crowdsec parse logs and found attacker ip more than 1 time and add it to decision list. In this case I've about 100k-200k of duplicated ip in crowdsec decision, and all of this duplicated ip custom bouncer try to ban via call api of external service. After some time, lag between bans is over 12hours, I mean custom bouncer baning ip, which decision was added 12 hours ago.
My sqlite db grows up over 600+mb

Do I need to increase blackhole time?
Or we need to prevent adding already banned ip into decision?

**Comment by buixor** [comment]
Hello @SanchosPancho !

Thanks for the issue.
Out of curiosity, is the "external api service" cloudflare api service by any chance ? (If so, I would strongly suggest looking at [our new cloudflare bouncer](https://github.com/crowdsecurity/cs-cloudflare-bouncer/).

If it's not the case, it's not a bug per se, but a known limitation of the custom bouncer. If you have no bouncer (or here a laggy one), offending IP can get banned more than once, and it is intended. However, while most of the bouncers take care of de-duplicating the received IPs (either because of the underlying mechanism ie. ipset or because it does it explicitly such as the cloudflare bouncer), the custom bouncer doesn't. (To be honest, it's a rather old bouncer that would deserve more love).


So, short term answer : Increasing the blackhole might avoid this. Medium term answer : while the custom bouncer stays in this state, maybe add a deduplication mechanism to your script. Medium++ term answer : we're gonna give some love to the custom bouncer :smile: 



ps: it's definitely a bag 

![image](https://user-images.githubusercontent.com/990714/120627886-69754980-c464-11eb-907d-e682912d74c5.png)

**Comment by SanchosPancho** [comment]
Hello @buixor, my mistake about bAg =)

In general I mean, why with shortest period of blackhole, crowdsec bans same ip more than 1 time? Hw about check already banned ip before add decision?

It doesn't matter will it custom bouncer or cloudflare bouncer, because cscli decisions have same ip more than 1 time, in my case 100+ per ip. 

About cloudflare bouncer, ip lists have a limit 10000 ip in total(if I'm not wrong), it's not enough for me, I've ban bad guys via account firewall rules for all websites on account. And cloudflare bouncer can ban only per zone, not per account is it right?

**Comment by buixor** [comment]
> In general I mean, why with shortest period of blackhole, crowdsec bans same ip more than 1 time? Hw about check already banned ip before add decision?

It is intentional design for various reasons, one of the first one being that if your counter measure fails : you use [cf bouncer](https://github.com/crowdsecurity/cs-cloudflare-bouncer) with captcha counter-measure, you *want* to know if the attacker manages to pass the captcha and continues to trigger attacks.

> It doesn't matter will it custom bouncer or cloudflare bouncer, because cscli decisions have same ip more than 1 time, in my case 100+ per ip.

It does matter : cf bouncer typically deduplicates the list of IPs it receives, and so does firewall bouncer (but for the latest, it's mostly thanks to ipset behavior).

> About cloudflare bouncer, ip lists have a limit 10000 ip in total(if I'm not wrong), it's not enough for me, I've ban bad guys via account firewall rules for all websites on account. And cloudflare bouncer can ban only per zone, not per account is it right?


Yes indeed, CF has a limit of 10K IPs *overall* in the lists, and using the firewall rules directly is not recommended by CF neither :/ However, if you're being hit but very strongly distributed attacks, answer might be to ban AS / Countries / Ranges rather than IPs individually (as I suppose you're being hit by a botnet or such).

We are currently working on this kind of scenarios and use-cases (attacking VPS with a botnet and stopping this attack with crowdsec + CF bouncer). Any chance we can get in touch to discuss about this ? Please reach us on [gitter](https://gitter.im/crowdsec-project/community) it would be cool !

**Comment by buixor** [comment]
Hello @SanchosPancho ! It has been implemented in custom bouncer https://github.com/crowdsecurity/cs-custom-bouncer/releases/tag/v0.0.8 :+1: I'm waiting for proper documentation and we should be good on this one (hopefully!)
